package org.usfirst.frc.team4911.steamworks.vision;

// http://docs.opencv.org/trunk/dd/d01/group__videoio__c.html
public final class VideoConstants {
	public static final int CV_CAP_PROP_DC1394_OFF = -4;
	public static final int CV_CAP_PROP_DC1394_MODE_MANUAL = -3;
	public static final int CV_CAP_PROP_DC1394_MODE_AUTO = -2;
	public static final int CV_CAP_PROP_DC1394_MODE_ONE_PUSH_AUTO = -1;
	public static final int CV_CAP_PROP_POS_MSEC = 0;
	public static final int CV_CAP_PROP_POS_FRAMES = 1;
	public static final int CV_CAP_PROP_POS_AVI_RATIO = 2;
	public static final int CV_CAP_PROP_FRAME_WIDTH = 3;
	public static final int CV_CAP_PROP_FRAME_HEIGHT = 4;
	public static final int CV_CAP_PROP_FPS = 5;
	public static final int CV_CAP_PROP_FOURCC = 6;
	public static final int CV_CAP_PROP_FRAME_COUNT = 7;
	public static final int CV_CAP_PROP_FORMAT = 8;
	public static final int CV_CAP_PROP_MODE = 9;
	public static final int CV_CAP_PROP_BRIGHTNESS = 10;
	public static final int CV_CAP_PROP_CONTRAST = 11;
	public static final int CV_CAP_PROP_SATURATION = 12;
	public static final int CV_CAP_PROP_HUE = 13;
	public static final int CV_CAP_PROP_GAIN = 14;
	public static final int CV_CAP_PROP_EXPOSURE = 15;
	public static final int CV_CAP_PROP_CONVERT_RGB = 16;
	public static final int CV_CAP_PROP_WHITE_BALANCE_BLUE_U = 17;
	public static final int CV_CAP_PROP_RECTIFICATION = 18;
	public static final int CV_CAP_PROP_MONOCHROME = 19;
	public static final int CV_CAP_PROP_SHARPNESS = 20;
	public static final int CV_CAP_PROP_AUTO_EXPOSURE = 21;
	public static final int CV_CAP_PROP_GAMMA = 22;
	public static final int CV_CAP_PROP_TEMPERATURE = 23;
	public static final int CV_CAP_PROP_TRIGGER = 24;
	public static final int CV_CAP_PROP_TRIGGER_DELAY = 25;
	public static final int CV_CAP_PROP_WHITE_BALANCE_RED_V = 26;
	public static final int CV_CAP_PROP_ZOOM = 27;
	public static final int CV_CAP_PROP_FOCUS = 28;
	public static final int CV_CAP_PROP_GUID = 29;
	public static final int CV_CAP_PROP_ISO_SPEED = 30;
	public static final int CV_CAP_PROP_MAX_DC1394 = 31;
	public static final int CV_CAP_PROP_BACKLIGHT = 32;
	public static final int CV_CAP_PROP_PAN = 33;
	public static final int CV_CAP_PROP_TILT = 34;
	public static final int CV_CAP_PROP_ROLL = 35;
	public static final int CV_CAP_PROP_IRIS = 36;
	public static final int CV_CAP_PROP_SETTINGS = 37;
	public static final int CV_CAP_PROP_BUFFERSIZE = 38;
	public static final int CV_CAP_PROP_AUTOFOCUS = 39;
	public static final int CV_CAP_PROP_SAR_NUM = 40;
	public static final int CV_CAP_PROP_SAR_DEN = 41;
	public static final int CV_CAP_PROP_AUTOGRAB = 1024;
	public static final int CV_CAP_PROP_SUPPORTED_PREVIEW_SIZES_STRING = 1025;
	public static final int CV_CAP_PROP_PREVIEW_FORMAT = 1026;
}
